### ISSUE TITLE
Taal is engels

### ISSUE THREAD

**Issue by SamaraFellaDina** [Daan645/b-rain#15]
https://github.com/Daan645/b-rain/blob/cbb2a958c9cbc1745bf6668dc3f208ddcaf68e90/index.html#L2C1-L2C1

**Comment by J3SS3HVA** [comment]
![Schermafbeelding 2023-10-11 102147](https://github.com/Daan645/b-rain/assets/144009667/aba3062b-6391-4292-b03c-f4ea968f2e00)

**Comment by J3SS3HVA** [comment]
op regel 2 van de index.html staat nu en (engels taal)
